---
name: Validate Manifest

on:
  #   push:
  #     paths:
  #       - "data/v2/manifest.json"
  #       - "data/v2/manifest.schema.json"
  pull_request:
    paths:
      - "data/v2/manifest.json"
      - "data/v2/manifest.schema.json"
  workflow_dispatch:

permissions: read-all

jobs:
  validate_manifest:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate manifest against schema
        run: npx ajv-cli validate -s data/v2/manifest.schema.json -d data/v2/manifest.json

      - name: Validate JSON syntax
        run: |
          npx prettier --check data/v2/manifest.json || (echo "Manifest JSON is invalid" && exit 1)
          npx prettier --check data/v2/manifest.schema.json || (echo "Manifest schema JSON is invalid" && exit 1)
